"""
Django settings for attendance_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = (
#     "django-insecure-8loxwz996nko-0ebyb2*=lnrslss$$8qaok@b&(o7dn7^re0n&"  # noqa
# )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
SECRET_KEY = os.getenv("SECRET_KEY")
ALLOWED_HOSTS = ["*"]


CSRF_TRUSTED_ORIGINS = ["https://*.onrender.com"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "attendance",
    "rest_framework",
]




MIDDLEWARE = [
    "attendance.middleware.CORSMiddleware",  # CORS for PHP frontend cross-origin requests
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # Language switcher
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "attendance.middleware.APIKeyAuthMiddleware",  # API Key auth for PHP frontend
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "attendance_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "attendance" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "attendance_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",  # noqa
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",  # noqa
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",  # noqa
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en"

TIME_ZONE = "Asia/Dhaka"

USE_I18N = True  # Enable internationalization
USE_L10N = True  # Enable localization

# Available languages for the admin interface
LANGUAGES = [
    ('en', _('English')),
    ('bn', _('বাংলা')),
    ('hi', _('हिन्दी')),
    ('es', _('Español')),
]

# Path to translation files
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

USE_TZ = True

DATETIME_FORMAT = "d/m/Y h:i:s A"  # dd/mm/yyyy 12-hour format with AM/PM
DATE_FORMAT = "d/m/Y"  # dd/mm/yyyy
SHORT_DATE_FORMAT = "d/m/Y"  # dd/mm/yyyy

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


ATTENDANCE_POLICY = {
    "LATE_THRESHOLD_FOR_FINE": 3,  # days late needed to trigger fine (integer)
    "FINE_AMOUNT": 1.0,  # days of salary to deduct (float or Decimal)
    "BONUS_IF_NO_LATE": True,  # enable/disable bonus
    "BONUS_AMOUNT": 50.00,  # fixed currency amount for bonus
}

# Mobile push configuration
FCM_SERVER_KEY = os.environ.get("FCM_SERVER_KEY", "")

# API Key for PHP frontend access (set via environment or default)
# Usage: Authorization: Key <API_KEY>
API_KEY = os.environ.get("DJANGO_API_KEY", "Key123")
