"""
Django settings for attendance_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (
    "django-insecure-8loxwz996nko-0ebyb2*=lnrslss$$8qaok@b&(o7dn7^re0n&"  # noqa
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.app",
    "https://*.ngrok-free.dev",
]

# Application definition

INSTALLED_APPS = [
    "jazzmin",  # Must be before django.contrib.admin
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "attendance",
    "rest_framework",
]


# Jazzmin Admin Theme Configuration
JAZZMIN_SETTINGS = {
    # Title on the login screen
    "site_title": "Attendance Admin",
    
    # Title on the brand (top left)
    "site_header": "Attendance System",
    
    # Title in browser tab
    "site_brand": "Attendance",
    
    # Welcome text on the login screen
    "welcome_sign": "Welcome to Attendance Management",
    
    # Copyright on the footer
    "copyright": "BaraBD Attendance System",
    
    # Field name on user model that contains avatar
    "user_avatar": None,
    
    # Top Menu (links at top of admin)
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "/", "new_window": True},
    ],
    
    # Side Menu
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Icons for apps/models
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "attendance.Employee": "fas fa-id-badge",
        "attendance.AttendanceRecord": "fas fa-calendar-check",
        "attendance.Shift": "fas fa-clock",
        "attendance.Holiday": "fas fa-calendar-day",
        "attendance.Organization": "fas fa-building",
        "attendance.OrganizationUser": "fas fa-user-tie",
    },
    
    # Default icon for apps not in icons dict
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    
    # Related modal (popup) instead of new page
    "related_modal_active": True,
    
    # Use Font Awesome icons
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
}

# Jazzmin UI Tweaks
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-success",
    "navbar": "navbar-dark navbar-success",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "attendance.middleware.APIKeyAuthMiddleware",  # API Key auth for PHP frontend
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "attendance_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "attendance" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "attendance_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",  # noqa
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",  # noqa
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",  # noqa
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Dhaka"

USE_I18N = False  # was False originally

USE_TZ = True

DATETIME_FORMAT = "d/m/Y h:i:s A"  # dd/mm/yyyy 12-hour format with AM/PM
DATE_FORMAT = "d/m/Y"  # dd/mm/yyyy
SHORT_DATE_FORMAT = "d/m/Y"  # dd/mm/yyyy

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


ATTENDANCE_POLICY = {
    "LATE_THRESHOLD_FOR_FINE": 3,  # days late needed to trigger fine (integer)
    "FINE_AMOUNT": 1.0,  # days of salary to deduct (float or Decimal)
    "BONUS_IF_NO_LATE": True,  # enable/disable bonus
    "BONUS_AMOUNT": 50.00,  # fixed currency amount for bonus
}

# Mobile push configuration
FCM_SERVER_KEY = os.environ.get("FCM_SERVER_KEY", "")

# API Key for PHP frontend access (set via environment or default)
# Usage: Authorization: Key <API_KEY>
API_KEY = os.environ.get("DJANGO_API_KEY", "Key123")
