# Generated by Django 5.2.7 on 2025-11-19 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_client_side_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 19, 5, 53, 3, 29618, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2025, 11, 19, 5, 54, 9, 206012, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
