# Generated by Django 5.2.7 on 2025-11-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0033_employee_bank_account_salarystatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarystatistic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
