# Generated by Django 5.2.7 on 2025-11-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0036_salarystatistic_use_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarystatisticdefault',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
