# Generated by Django 5.2.7 on 2025-11-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0037_add_stamp_to_salary_statistic'),
        ('attendance', '0037_alter_salarystatisticdefault_id'),
    ]

    operations = [
    ]
