# Generated by Django 5.2.7 on 2025-11-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0042_merge_0040_remove_tds_amount_from_default_0041_remove_tds_amount_from_salary_statistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarystatisticdefault',
            name='attended_days',
        ),
        migrations.RemoveField(
            model_name='salarystatisticdefault',
            name='holidays',
        ),
        migrations.RemoveField(
            model_name='salarystatisticdefault',
            name='leave_days',
        ),
        migrations.RemoveField(
            model_name='salarystatisticdefault',
            name='weekends',
        ),
        migrations.RemoveField(
            model_name='salarystatisticdefault',
            name='working_days',
        ),
    ]
