# Generated by Django 5.2.7 on 2025-11-27 08:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0043_remove_salarystatisticdefault_attended_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarystatistic',
            name='other_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
