# Generated by Django 5.2.7 on 2025-11-27 09:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0044_salarystatistic_other_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarystatistic',
            name='auto_calculate_bonus',
            field=models.BooleanField(default=True, help_text='If True, bonus is calculated automatically based on 100% attendance.'),
        ),
        migrations.AddField(
            model_name='salarystatistic',
            name='auto_calculate_fine',
            field=models.BooleanField(default=True, help_text='If True, fine is calculated automatically (1 day salary per 3 late days).'),
        ),
        migrations.AddField(
            model_name='salarystatistic',
            name='late_fine',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystatisticdefault',
            name='auto_calculate_bonus',
            field=models.BooleanField(default=True, help_text='If True, bonus is calculated automatically based on 100% attendance.'),
        ),
        migrations.AddField(
            model_name='salarystatisticdefault',
            name='auto_calculate_fine',
            field=models.BooleanField(default=True, help_text='If True, fine is calculated automatically (1 day salary per 3 late days).'),
        ),
        migrations.AddField(
            model_name='salarystatisticdefault',
            name='late_fine',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
