# Generated by Django 5.2.7 on 2025-11-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0045_salarystatistic_auto_calculate_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarystatistic',
            name='late_needed',
            field=models.PositiveIntegerField(default=0, help_text='Number of late days to trigger one fine unit'),
        ),
        migrations.AddField(
            model_name='salarystatistic',
            name='present_needed',
            field=models.PositiveIntegerField(default=0, help_text='Minimum days present required for bonus'),
        ),
        migrations.AddField(
            model_name='salarystatisticdefault',
            name='late_needed',
            field=models.PositiveIntegerField(default=0, help_text='Number of late days to trigger one fine unit'),
        ),
        migrations.AddField(
            model_name='salarystatisticdefault',
            name='present_needed',
            field=models.PositiveIntegerField(default=0, help_text='Minimum days present required for bonus'),
        ),
        migrations.AlterField(
            model_name='salarystatistic',
            name='auto_calculate_bonus',
            field=models.BooleanField(default=True, help_text='If True, bonus is calculated automatically based on present_needed.'),
        ),
        migrations.AlterField(
            model_name='salarystatistic',
            name='auto_calculate_fine',
            field=models.BooleanField(default=True, help_text='If True, fine is calculated automatically (late_days // late_needed * late_fine).'),
        ),
        migrations.AlterField(
            model_name='salarystatisticdefault',
            name='auto_calculate_bonus',
            field=models.BooleanField(default=True, help_text='If True, bonus is calculated automatically based on present_needed.'),
        ),
        migrations.AlterField(
            model_name='salarystatisticdefault',
            name='auto_calculate_fine',
            field=models.BooleanField(default=True, help_text='If True, fine is calculated automatically (late_days // late_needed * late_fine).'),
        ),
    ]
