# Generated by Django 5.2.7 on 2025-11-27 09:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0046_salarystatistic_late_needed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarystatistic',
            name='present_needed',
        ),
        migrations.RemoveField(
            model_name='salarystatisticdefault',
            name='present_needed',
        ),
        migrations.AddField(
            model_name='salarystatistic',
            name='required_attendance_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum attendance percentage required for bonus', max_digits=5),
        ),
        migrations.AddField(
            model_name='salarystatisticdefault',
            name='required_attendance_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum attendance percentage required for bonus', max_digits=5),
        ),
        migrations.AlterField(
            model_name='salarystatistic',
            name='auto_calculate_bonus',
            field=models.BooleanField(default=True, help_text='If True, bonus is calculated automatically based on required_attendance_percent.'),
        ),
        migrations.AlterField(
            model_name='salarystatisticdefault',
            name='auto_calculate_bonus',
            field=models.BooleanField(default=True, help_text='If True, bonus is calculated automatically based on required_attendance_percent.'),
        ),
    ]
