# Generated by Django 5.2.7 on 2025-11-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0047_remove_salarystatistic_present_needed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarystatistic',
            name='auto_calculate_bonus',
        ),
        migrations.RemoveField(
            model_name='salarystatistic',
            name='auto_calculate_fine',
        ),
        migrations.RemoveField(
            model_name='salarystatisticdefault',
            name='auto_calculate_bonus',
        ),
        migrations.RemoveField(
            model_name='salarystatisticdefault',
            name='auto_calculate_fine',
        ),
    ]
