# Generated by Django 5.2.7 on 2025-11-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0048_remove_salarystatistic_auto_calculate_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_status_override',
            field=models.BooleanField(default=False, help_text='If True, status is manually set and will not be auto-calculated.'),
        ),
    ]
