# Generated by Django 5.2.7 on 2025-11-30 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0049_attendancerecord_is_status_override'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalaryAdjustment',
        ),
    ]
