# Generated by Django 5.2.7 on 2025-12-02 03:12

import attendance.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0053_companyinfo_tin_bin_founder'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveFeedStub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Live Feed',
                'verbose_name_plural': 'Live Feed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LiveFeedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=attendance.models.livefeed_image_path)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('captured_at', models.DateTimeField(db_index=True, default=attendance.models.dhaka_now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livefeed_images', to='attendance.employee')),
            ],
            options={
                'ordering': ('-captured_at', '-id'),
                'indexes': [models.Index(fields=['captured_at'], name='attendance__capture_df0e5f_idx'), models.Index(fields=['employee', 'captured_at'], name='attendance__employe_5763a8_idx')],
            },
        ),
    ]
