# Generated by Django 5.2.7 on 2025-12-02 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0054_livefeedstub_livefeedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='livefeedimage',
            name='subject_identifier',
            field=models.CharField(db_index=True, default='unknown', help_text="Employee ID used for quota; 'unknown' when not matched", max_length=100),
        ),
        migrations.AlterField(
            model_name='livefeedimage',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livefeed_images', to='attendance.employee'),
        ),
        migrations.AddIndex(
            model_name='livefeedimage',
            index=models.Index(fields=['subject_identifier', 'captured_at'], name='attendance__subject_2f6778_idx'),
        ),
    ]
