# Generated by Django 5.2.7 on 2025-12-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0055_livefeedimage_subject_identifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_language', models.CharField(default='en-US', help_text='Primary TTS locale (e.g., en-US, bn-BD, hi-IN, zh-CN, ko-KR, ja-JP).', max_length=16)),
                ('additional_languages', models.JSONField(blank=True, default=list, help_text='List of fallback locales in priority order.')),
                ('name_format', models.CharField(choices=[('full', 'Full Name'), ('first', 'First Name'), ('last', 'Last Name'), ('custom', 'Custom Template')], default='full', help_text='How names should be spoken in voice prompts.', max_length=12)),
                ('custom_name_template', models.CharField(blank=True, help_text='Use {first}, {last}, {full} placeholders when name_format is custom.', max_length=64)),
                ('speech_rate', models.FloatField(default=1.0, help_text='TTS speech rate (1.0 = normal).')),
                ('pitch', models.FloatField(default=1.0, help_text='TTS pitch (1.0 = normal).')),
                ('voice_mode', models.CharField(choices=[('default', 'Default'), ('calm', 'Calm'), ('energetic', 'Energetic'), ('slow', 'Slow')], default='default', help_text='Optional mode hint for the client.', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
