# Generated by Django 5.2.7 on 2025-12-02 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0056_voicesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_message_display', models.BooleanField(default=True)),
                ('voice_message_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextMessageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_text', models.CharField(default='Welcome {name}', max_length=255)),
                ('checkout_text', models.CharField(default='Goodbye {name}', max_length=255)),
                ('checkin_interval_seconds', models.FloatField(default=3.0)),
                ('checkout_interval_seconds', models.FloatField(default=3.0)),
                ('checkin_active', models.BooleanField(default=True)),
                ('checkout_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.contextsetting')),
                ('voice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.voicesetting')),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.textmessagesetting')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceNameOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(default='en-US', max_length=16)),
                ('spoken_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_names', to='attendance.employee')),
            ],
            options={
                'ordering': ('employee__employee_id', 'language_code'),
                'unique_together': {('employee', 'language_code')},
            },
        ),
    ]
