# Generated by Django 5.2.7 on 2025-12-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0057_contextsetting_textmessagesetting_messagesetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoicePhraseOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(default='en-US', max_length=16)),
                ('checkin_phrase', models.CharField(default='Welcome {name}', help_text='Use {name} placeholder', max_length=255)),
                ('checkout_phrase', models.CharField(default='Goodbye {name}', help_text='Use {name} placeholder', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('language_code',),
                'unique_together': {('language_code',)},
            },
        ),
    ]
