# Generated by Django 5.2.7 on 2025-12-02 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0058_voicephraseoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesetting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='messagesetting',
            name='name',
            field=models.CharField(default='Default', max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='EmployeeVoicePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(default='en-US', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_preference', to='attendance.employee')),
            ],
        ),
    ]
