# Generated by Django 5.2.7 on 2025-12-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0058_voicephraseoverride'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagesetting',
            options={'managed': False},
        ),
    ]
