# Generated by Django 5.2.9 on 2025-12-10 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0062_alter_voicesetting_voice_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Assigned shift for this employee', null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.shift'),
        ),
    ]
