# Generated by Django 5.2.7 on 2025-12-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0063_employee_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkholiday',
            options={'ordering': ('-created_at',), 'verbose_name': 'Holiday', 'verbose_name_plural': 'Holidays'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='shift',
        ),
    ]
