# Generated by Django 5.2.9 on 2025-12-15 07:01

import attendance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0064_alter_bulkholiday_options_remove_employee_shift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text="URL-friendly identifier, e.g., 'company-abc'", unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=attendance.models.organization_logo_path)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this organization is active')),
                ('max_employees', models.PositiveIntegerField(default=100, help_text='Maximum employees allowed (license limit)')),
                ('max_devices', models.PositiveIntegerField(default=5, help_text='Maximum devices allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='livefeedimage',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_livefeed_images', to='attendance.employee'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, help_text='Unique identifier sent by APK (configured in app settings)', max_length=100, unique=True)),
                ('device_name', models.CharField(help_text="Human-readable name, e.g., 'Main Gate Tablet'", max_length=255)),
                ('location', models.CharField(blank=True, help_text="Physical location, e.g., 'Main Entrance'", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, help_text='Last time this device made an API call', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(help_text='Organization this device belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='attendance.organization')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['organization', 'device_name'],
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.organization'),
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this employee belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='attendance.organization'),
        ),
        migrations.AddField(
            model_name='livefeedimage',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this image belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livefeed_images', to='attendance.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=50)),
                ('work_week_start', models.PositiveIntegerField(default=0, help_text='0=Sunday, 1=Monday, etc.')),
                ('liveness_threshold', models.FloatField(default=0.7)),
                ('match_threshold', models.FloatField(default=0.8)),
                ('default_voice_language', models.CharField(default='en', max_length=10)),
                ('voice_enabled', models.BooleanField(default=True)),
                ('email_on_late', models.BooleanField(default=False)),
                ('email_on_absent', models.BooleanField(default=False)),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='attendance.organization')),
            ],
            options={
                'verbose_name': 'Organization Settings',
                'verbose_name_plural': 'Organization Settings',
            },
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('org_admin', 'Organization Admin'), ('org_viewer', 'Organization Viewer')], default='org_viewer', max_length=20)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this user belongs to. Null for super admins.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='attendance.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization User',
                'verbose_name_plural': 'Organization Users',
            },
        ),
    ]
