# Generated by Django 5.2.9 on 2025-12-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0070_create_default_plans'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_org_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_user_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_action_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_resource_ts_idx',
        ),
        migrations.RemoveField(
            model_name='bulkholiday',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='contextsetting',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='moderatorlabel',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='subscription_expires',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='subscription_started',
        ),
        migrations.RemoveField(
            model_name='salarystatisticdefault',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='voicesetting',
            name='organization',
        ),
        migrations.AddField(
            model_name='organization',
            name='bin',
            field=models.CharField(blank=True, help_text='Business Identification Number', max_length=100, null=True, verbose_name='BIN / BFN'),
        ),
        migrations.AddField(
            model_name='organization',
            name='founder',
            field=models.CharField(blank=True, help_text='Founder/Owner name for reports', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='tin',
            field=models.CharField(blank=True, help_text='Tax Identification Number', max_length=100, null=True, verbose_name='TIN'),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, help_text='Company website URL', null=True),
        ),
    ]
