# Generated by Django 5.2.9 on 2025-12-20 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0071_add_company_info_fields_to_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Subscription plan for this organization (overrides default limits)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='attendance.subscriptionplan'),
        ),
    ]
