# Generated by Django 5.2.9 on 2025-12-20 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0072_add_plan_to_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this org user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_org_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='is_main_admin',
            field=models.BooleanField(default=False, help_text='If true, this user is the primary admin and cannot be deleted'),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('org_main_admin', 'Organization Main Admin'), ('org_admin', 'Organization Admin'), ('org_viewer', 'Organization Viewer')], default='org_viewer', max_length=20),
        ),
    ]
