# Generated by Django 5.2.9 on 2025-12-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0073_add_org_admin_hierarchy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationuser',
            name='is_main_admin',
        ),
    ]
