# Generated by Django 5.2.9 on 2025-12-24 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0074_simplify_org_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkholiday',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='attendance.organization'),
        ),
    ]
