# Generated by Django 5.2.9 on 2025-12-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0076_shift_organization_alter_shift_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='absent_after_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Minutes after shift start when employee is marked absent if not checked in'),
        ),
    ]
