# Generated by Django 5.2.9 on 2025-12-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0077_add_absent_after_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('shadow_admin', 'System'), ('org_main_admin', 'Organization Main Admin'), ('org_admin', 'Organization Admin'), ('org_viewer', 'Organization Viewer')], default='org_viewer', max_length=20),
        ),
    ]
