# Generated by Django 5.2.9 on 2025-12-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0078_add_shadow_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='ot_active_after',
            field=models.TimeField(blank=True, help_text='Time after which overtime starts counting (should be after shift_end)', null=True),
        ),
    ]
