# Generated by Django 5.2.7 on 2026-02-18 04:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0079_add_ot_active_after_to_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarystatistic',
            name='absent_fine',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Per-day absent fine amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystatisticdefault',
            name='absent_fine',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Per-day absent fine amount', max_digits=12),
        ),
    ]
